config/routes.rb
Rails.application.routes.draw do
  resources :savermarts, path: 'savermarts' do
    collection { 
      get :index , via: :options
      post :create , via: :options  
      put :update , via: :options 
      delete :destroy , via: :options
    }
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/savermart.rb
class Savermart < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/savermarts_controller.rb
class SavermartsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_savermart, only: %i[ show edit update destroy ]

  # GET /savermarts or /savermarts.json
  def index
    @savermarts = Savermart.all
    render json: @savermarts
  end

  # GET /savermarts/1 or /savermarts/1.json
  def show
  end

  # GET /savermarts/new
  def new
    @savermart = Savermart.new
  end

  # GET /savermarts/1/edit
  def edit
  end

  # POST /savermarts or /savermarts.json
  def create
    @savermart = Savermart.new(savermart_params)

    respond_to do |format|
      if @savermart.save
        format.html { redirect_to savermart_url(@savermart), notice: "Savermart was successfully created." }
        format.json { render :show, status: :created, location: @savermart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @savermart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /savermarts/1 or /savermarts/1.json
  def update
    respond_to do |format|
      if @savermart.update(savermart_params)
        format.html { redirect_to savermart_url(@savermart), notice: "Savermart was successfully updated." }
        format.json { render :show, status: :ok, location: @savermart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @savermart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /savermarts/1 or /savermarts/1.json
  def destroy
    @savermart.destroy

    respond_to do |format|
      format.html { redirect_to savermarts_url, notice: "Savermart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_savermart
      @savermart = Savermart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def savermart_params
      params.require(:savermart).permit(
        :name,
        :display,
        :ram,
        :battery,
        :back_camera,
        :release_date,
        :sim_support,
        :phone_dimensions,
        :phone_weight,
        :operating_system,
        :processor,
        :gpu,
        :screen_size,
        :screen_resolution,
        :screen_type,
        :screen_protection,
        :front_camera,
        :front_flashlight,
        :front_video_recording,
        :back_flashlight,
        :back_video_recording,
        :internal_memory,
        :card_slot,
        :battery_type,
        :bluetooth,
        :G3,
        :G4,
        :G5,
        :radio,
        :wifi,
        :nfc,
        :faq,
        :box,
        :cond
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/savermarts_helper.rb
module SavermartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EbayListingBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/savermarts/_form.html.erb
<%= form_with(model: savermart) do |form| %>
  <% if savermart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(savermart.errors.count, "error") %> prohibited this savermart from being saved:</h2>

      <ul>
        <% savermart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/savermarts/edit.html.erb
<h1>Editing Savermart</h1>

<%= render 'form', savermart: @savermart %>

<%= link_to 'Show', @savermart %> |
<%= link_to 'Back', savermarts_path %>

app/views/savermarts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Savermarts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savermarts.each do |savermart| %>
      <tr>
        <td><%= link_to 'Show', savermart %></td>
        <td><%= link_to 'Edit', edit_savermart_path(savermart) %></td>
        <td><%= link_to 'Destroy', savermart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Savermart', new_savermart_path %>

app/views/savermarts/new.html.erb
<h1>New Savermart</h1>

<%= render 'form', savermart: @savermart %>

<%= link_to 'Back', savermarts_path %>

app/views/savermarts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_savermart_path(@savermart) %> |
<%= link_to 'Back', savermarts_path %>